setwd("E:/Post Graduation/Trimester 2/R/Project")
library("rjson")
library("stringr")
library("zoom")
library("maptools")
library("raster")
source(file = "LoadingData.R")
source(file = "ExtractLabel.R")
source(file = "ExtractData.R")
source(file = "CreateDataSet.R")
source(file = "Operations.R")
